[package]
name = "stats_provider"
version = "0.5.2"
description = "A simple system stats event provider for Sketchybar."
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
sketchybar-rs = "0.2.0"
sysinfo = "0.31.4"
